//socket connection
export const CONNECT_TO_WEBSOCKET="CONNECT_TO_WEBSOCKET";
export const NEW_ONLINE_USERS="NEW_ONLINE_USERS";
export const WEB_SOCKET_CONNECT_SUCCESS="WEB_SOCKET_CONNECT_SUCCESS";
export const WEB_SOCKET_CONNECT_FAILURE="WEB_SOCKET_CONNECT_FAILURE";
export const WEBSOCKET_MESSAGE_RECEIVED="WEBSOCKET_MESSAGE_RECEIVED";
export const ONLINE_USERS="ONLINE_USERS";
export const CHANGE_USER_STATUS="CHANGE_USER_STATUS";
export const CHANGE_USER_STATUS_SUCCESS="CHANGE_USER_STATUS_SUCCESS";
export const GET_PRODUCT_DETAIL="GET_PRODUCT_DETAIL";
//User Api
export const USER_API_CALL_REQUEST = "USER_API_CALL_REQUEST";
export const USER_API_CALL_SUCCESS = "USER_API_CALL_SUCCESS";
export const USER_API_CALL_FAILURE = "USER_API_CALL_FAILURE";

export const User_DATA_Call_Request = "USER_DATA_CALL_REQUEST";
export const User_DATA_Call_SUCCESS = "USER_DATA_CALL_SUCCESS";
export const User_DATA_Call_FAILURE = "USER_DATA_CALL_FAILURE";

export const USER_REGISTER_CALL_REQUEST = "USER_REGISTER_CALL_REQUEST";
export const USER_REGISTER_CALL_SUCCESS="USER_REGISTER_CALL_SUCCESS";
export const USER_REGISTER_CALL_FAILURE="USER_REGISTER_CALL_FAILURE";

export const User_Filter_Call_Request = "USER_FILTER_CALL_REQUEST";
export const User_Filter_Call_SUCCESS = "USER_FILTER_CALL_SUCCESS";
export const User_Filter_Call_FAILURE = "USER_FILTER_CALL_FAILURE";

export const USER_PROFILE_DETAILS_CALL_REQUEST = "USER_PROFILE_DETAILS_CALL_REQUEST";
export const USER_PROFILE_DETAILS_CALL_SUCCESS="USER_PROFILE_DETAILS_CALL_SUCCESS";
export const USER_PROFILE_DETAILS_CALL_FAILURE="USER_PROFILE_DETAILS_CALL_FAILURE";

export const USER_TABLE_CSV="USER_TABLE_CSV";
export const USER_TABLE_SUCCESS="USER_TABLE_EXPORT_CSV_SUCCESS";
export const USER_TABLE_FAILURE="USER_TABLE_EXPORT_CSV_FAILURE";



export const GET_PRODUCTS_CALL_REQUEST="GET_PRODUCTS_CALL_REQUEST";
export const GET_PRODUCTS_CALL_SUCCESS="GET_PRODUCTS_CALL_SUCCESS";
export const GET_PRODUCTS_CALL_FAILURE="GET_PRODUCTS_CALL_FAILURE";


export const ADD_PRODUCT_CONTENT_REQUEST="ADD_PRODUCT_CONTENT_REQUEST";
export const REQUEST_SUCCESS="REQUEST_SUCCESS";
export const REQUEST_FAILURE="REQUEST_FAILURE";


export const EDIT_PRODUCT_CONTENT_REQUEST="EDIT_PRODUCT_CONTENT_REQUEST";


export const GET_CATEGORY_CALL_REQUEST="GET_CATEGORY_CALL_REQUEST";
export const GET_CATEGORY_CALL_SUCCESS="GET_CATEGORY_CALL_SUCCESS";
export const GET_CATEGORY_CALL_FAILURE="GET_CATEGORY_CALL_FAILURE";


export const ADD_PRODUCT_CATEGORY_REQUEST="ADD_PRODUCT_CATEGORY_REQUEST";
export const ADD_CATEGORY_REQUEST_SUCCESS="ADD_CATEGORY_REQUEST_SUCCESS";
export const ADD_PRODUCT_CATEGORY_REQUEST_FAILURE="ADD_PRODUCT_CATEGORY_REQUEST_FAILURE";


export const HANDLE_CATEGORY_AUTOFILL_REQUEST="HANDLE_CATEGORY_AUTOFILL_REQUEST";
export const CATEGORY_AUTOFILL_SUCCESS="CATEGORY_AUTOFILL_SUCCESS";
export const CATEGORY_AUTOFILL_FAILURE="CATEGORY_AUTOFILL_FAILURE";



export const EDIT_PRODUCT_CATEGORY_REQUEST="EDIT_PRODUCT_CATEGORY_REQUEST";
export const EDIT_PRODUCT_CATEGORY_REQUEST_SUCCESS="EDIT_PRODUCT_CATEGORY_REQUEST_SUCCESS";
export const EDIT_PRODUCT_CATEGORY_REQUEST_FAILURE="EDIT_PRODUCT_CATEGORY_REQUEST_FAILURE";


export const GET_SUPPLIERS_CALL_REQUEST="GET_SUPPLIERS_CALL_REQUEST";
export const GET_SUPPLIERS_CALL_SUCCESS="GET_SUPPLIERS_CALL_SUCCESS";
export const GET_SUPPLIERS_CALL_FAILURE="GET_SUPPLIERS_CALL_FAILURE";


export const GET_LOCATION_DATA="GET_LOCATION_DATA"
export const GET_LOCATION_DATA_SUCCESS="GET_LOCATION_DATA_SUCCESS"
export const GET_LOCATION_DATA_FAILURE="GET_LOCATION_DATA_FAILURE"



export const ADD_PRODUCT_SUPPLIER_REQUEST="ADD_PRODUCT_SUPPLIER_REQUEST";
export const ADD_PRODUCT_SUPPLIER_REQUEST_SUCCESS="ADD_PRODUCT_SUPPLIER_REQUEST_SUCCESS";
export const ADD_PRODUCT_SUPPLIER_REQUEST_FAILURE="ADD_PRODUCT_SUPPLIER_REQUEST_FAILURE";


export const EDIT_PRODUCT_SUPPLIER_REQUEST="EDIT_PRODUCT_SUPPLIER_REQUEST";
export const EDIT_PRODUCT_SUPPLIER_REQUEST_SUCCESS="EDIT_PRODUCT_SUPPLIER_REQUEST_SUCCESS";
export const EDIT_PRODUCT_SUPPLIER_REQUEST_FAILURE="EDIT_PRODUCT_SUPPLIER_REQUEST_FAILURE";


export const GET_BRANDS_CALL_REQUEST="GET_BRANDS_CALL_REQUEST";
export const GET_BRANDS_CALL_SUCCESS="GET_BRANDS_CALL_SUCCESS";
export const GET_BRANDS_CALL_FAILURE="GET_BRANDS_CALL_FAILURE";


export const ADD_PRODUCT_BRAND_REQUEST="ADD_PRODUCT_BRAND_REQUEST";
export const ADD_PRODUCT_BRAND_REQUEST_SUCCESS="ADD_PRODUCT_BRAND_REQUEST_SUCCESS";
export const ADD_PRODUCT_BRAND_REQUEST_FAILURE="ADD_PRODUCT_BRAND_REQUEST_FAILURE";


export const CREATE_AUCTION_REQUEST="CREATE_AUCTION_REQUEST";
export const CREATE_AUCTION_REQUEST_SUCCESS="CREATE_AUCTION_REQUEST_SUCCESS";
export const CREATE_AUCTION_REQUEST_FAILURE="CREATE_AUCTION_REQUEST_FAILURE";


export const UPDATE_AUCTION_REQUEST="UPDATE_AUCTION_REQUEST";
export const UPDATE_AUCTION_REQUEST_SUCCESS="UPDATE_AUCTION_REQUEST_SUCCESS";
export const UPDATE_AUCTION_REQUEST_FAILURE="UPDATE_AUCTION_REQUEST_FAILURE";


export const AUCTION_PRODUCT_LIST_REQUEST="AUCTION_PRODUCT_LIST_REQUEST";
export const AUCTION_PRODUCT_LIST_REQUEST_SUCCESS="AUCTION_PRODUCT_LIST_REQUEST_SUCCESS";
export const AUCTION_PRODUCT_LIST_REQUEST_FAILURE="AUCTION_PRODUCT_LIST_REQUEST_FAILURE";

export const EDIT_PRODUCT_BRAND_REQUEST="EDIT_PRODUCT_BRAND_REQUEST";
export const EDIT_PRODUCT_BRAND_REQUEST_SUCCESS="EDIT_PRODUCT_BRAND_REQUEST_SUCCESS";
export const EDIT_PRODUCT_BRAND_REQUEST_FAILURE="EDIT_PRODUCT_BRAND_REQUEST_FAILURE";

export const BANK_DETAILS_FILTER_REQUEST="BANK_DETAILS_FILTER_REQUEST";
export const BANK_DETAILS_FILTER_SUCCESS="BANK_DETAILS_FILTER_SUCCESS";
export const BANK_DETAILS_FILTER_FAILURE="BANK_DETAILS_FILTER_FAILURE"

export const BID_PACKAGE_DATA_REQUEST="BID_PACKAGE_DATA_REQUEST";
export const BID_PACKAGE_DATA_SUCCESS="BID_PACKAGE_DATA_SUCCESS";
export const BID_PACKAGE_DATA_FAILURE="BID_PACKAGE_DATA_FAILURE"
export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_REQUEST_SUCCESS="PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAILURE="PRODUCT_LIST_REQUEST_FAILURE";

export const AUCTION_LIST_FILTER_REQUEST="AUCTION_LIST_FILTER_REQUEST";
export const AUCTION_LIST_FILTER_REQUEST_SUCCESS="AUCTION_LIST_FILTER_REQUEST_SUCCESS";
export const AUCTION_LIST_FILTER_REQUEST_FAILURE="AUCTION_LIST_FILTER_REQUEST_FAILURE";

export const ADD_BANK_REQUEST="ADD_BANK_REQUEST";
export const ADD_BANK_SUCCESS="ADD_BANK_SUCCESS";
export const ADD_BANK_FAILURE="ADD_BANK_FAILURE";

export const UPDATE_AMOUNT_REQUEST="UPDATE_AMOUNT_REQUEST"
export const UPDATE_AMOUNT_SUCCESS="UPDATE_AMOUNT_SUCCESS"
export const UPDATE_AMOUNT_FAILURE="UPDATE_AMOUNT_FAILURE"

export const UPDATE_AMOUNT_IN_STORE="UPDATE_AMOUNT_IN_STORE";
export const UPDATE_AMOUNT_IN_STORE_SUCCESS="UPDATE_AMOUNT_IN_STORE_SUCCESS";

export const UPDATE_AMOUNT_IN_INPUT="UPDATE_AMOUNT_IN_INPUT"
export const UPDATE_AMOUNT_IN_INPUT_SUCCESS="UPDATE_AMOUNT_IN_INPUT_SUCCESS"

export const DATA_BIDS_BY_BANK_REQUEST="DATA_BIDS_BY_BANK_REQUEST";
export const DATA_BIDS_BY_BANK_SUCCESS="DATA_BIDS_BY_BANK_SUCCESS";
export const DATA_BIDS_BY_BANK_FAILURE="DATA_BIDS_BY_BANK_FAILURE";

export const PAYMENT_DETAILS_DATA_REQUEST="PAYMENT_DETAILS_DATA_REQUEST";
export const PAYMENT_DETAILS_DATA_SUCCESS="PAYMENT_DETAILS_DATA_SUCCESS";
export const PAYMENT_DETAILS_DATA_FAILURE="PAYMENT_DETAILS_DATA_FAILURE"

export const UPDATE_SELECT_VALUE='UPDATE_SELECT_VALUE';
export const UPDATE_SELECT_VALUE_SUCCESS='UPDATE_SELECT_VALUE_SUCCESS';

export const EDIT_BANK_REQUEST="EDIT_BANK_REQUEST"





/*---------------------------Review Content Actions---------------------------------------------->*/
export const GET_PACKAGE_REQUEST='GET_PACKAGE_REQUEST'
export const GET_PACKAGE_SUCCESS='GET_PACKAGE_SUCCESS'
export const GET_PACKAGE_FAILURE='GET_PACKAGE_FAILURE'

export const ADD_REVIEW_REQUEST='ADD_REVIEW_REQUEST'
export const ADD_REVIEW_SUCCESS='ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAILURE='ADD_REVIEW_FAILURE'


export const GET_REVIEW_REQUEST='GET_REVIEW_REQUEST'
export const GET_REVIEW_SUCCESS='GET_REVIEW_SUCCESS'
export const GET_REVIEW_FAILURE='GET_REVIEW_FAILURE'


export const ADD_REVIEW_PERMISSION_REQUEST='ADD_REVIEW_PERMISSION_REQUEST'
export const ADD_REVIEW_PERMISSION_SUCCESS='ADD_REVIEW_PERMISSION_SUCCESS'
export const ADD_REVIEW_PERMISSION_FAILURE='ADD_REVIEW_PERMISSION_FAILURE'



export const GET_REVIEW_PERMISSION_REQUEST='GET_REVIEW_PERMISSION_REQUEST'
export const GET_REVIEW_PERMISSION_SUCCESS='GET_REVIEW_PERMISSION_SUCCESS'
export const GET_REVIEW_PERMISSION_FAILURE='GET_REVIEW_PERMISSION_FAILURE'



/*---------------------------TRADE EXCHANGE Content Actions---------------------------------------------->*/
export const GET_TRADE_OUT_CONTENT_REQUEST='GET_TRADE_OUT_CONTENT_REQUEST'
export const GET_TRADE_OUT_CONTENT_SUCCESS='GET_TRADE_OUT_CONTENT_SUCCESS'
export const GET_TRADE_OUT_CONTENT_FAILURE='GET_TRADE_OUT_CONTENT_FAILURE'


export const GET_PAYMENT_CONTENT_REQUEST='GET_PAYMENT_CONTENT_REQUEST'
export const GET_PAYMENT_CONTENT_SUCCESS='GET_PAYMENT_CONTENT_SUCCESS'
export const GET_PAYMENT_CONTENT_FAILURE='GET_PAYMENT_CONTENT_FAILURE'


export const GET_TRADE_STATUS_CONTENT_REQUEST='GET_TRADE_STATUS_CONTENT_REQUEST'
export const GET_TRADE_STATUS_CONTENT_SUCCESS='GET_TRADE_STATUS_CONTENT_SUCCESS'
export const GET_TRADE_STATUS_CONTENT_FAILURE='GET_TRADE_STATUS_CONTENT_FAILURE'



/*---------------------------COUPON Content Actions---------------------------------------------->*/
export const GET_COUPON_PACKAGE_REQUEST='GET_COUPON_PACKAGE_REQUEST'
export const GET_COUPON_PACKAGE_SUCCESS='GET_COUPON_PACKAGE_SUCCESS'
export const GET_COUPON_PACKAGE_FAILURE='GET_COUPON_PACKAGE_FAILURE'


export const ADD_COUPON_PACKAGE_REQUEST='ADD_COUPON_PACKAGE_REQUEST'
export const ADD_COUPON_PACKAGE_SUCCESS='ADD_COUPON_PACKAGE_SUCCESS'
export const ADD_COUPON_PACKAGE_FAILURE='ADD_COUPON_PACKAGE_FAILURE'

export const GET_ALL_COUPONS_REQUEST="GET_ALL_COUPONS_REQUEST"
export const GET_ALL_COUPONS_SUCCESS="GET_ALL_COUPONS_SUCCESS"
export const GET_ALL_COUPONS_FAILURE="GET_ALL_COUPONS_FAILURE"

export const GET_COUPON_PERMISSION_REQUEST='GET_COUPON_PERMISSION_REQUEST'
export const GET_COUPON_PERMISSION_SUCCESS='GET_COUPON_PERMISSION_SUCCESS'
export const GET_COUPON_PERMISSION_FAILURE='GET_COUPON_PERMISSION_FAILURE'

export const ADD_COUPON_PERMISSION_REQUEST='ADD_COUPON_PERMISSION_REQUEST'
export const ADD_COUPON_PERMISSION_SUCCESS='ADD_COUPON_PERMISSION_SUCCESS'
export const ADD_COUPON_PERMISSION_FAILURE='ADD_COUPON_PERMISSION_FAILURE'




/*---------------------------REPORTS Content Actions---------------------------------------------->*/
export const GET_DEPOSIT_REPORT_REQUEST='GET_DEPOSIT_REPORT_REQUEST'
export const GET_DEPOSIT_REPORT_SUCCESS='GET_DEPOSIT_REPORT_SUCCESS'
export const GET_DEPOSIT_REPORT_FAILURE='GET_DEPOSIT_REPORT_FAILURE'


export const GET_TRADE_REPORT_REQUEST='GET_TRADE_REPORT_REQUEST'
export const GET_TRADE_REPORT_SUCCESS='GET_TRADE_REPORT_SUCCESS'
export const GET_TRADE_REPORT_FAILURE='GET_TRADE_REPORT_FAILURE'






/*---------------------------COUPON Content Actions---------------------------------------------->*/
export const GET_DEPARTMENT_DATA_REQUEST='GET_DEPARTMENT_DATA_REQUEST'
export const GET_DEPARTMENT_DATA_SUCCESS='GET_DEPARTMENT_DATA_SUCCESS'
export const GET_DEPARTMENT_DATA_FAILURE='GET_DEPARTMENT_DATA_FAILURE'

export const GET_EMPLOYEES_DATA_REQUEST='GET_EMPLOYEES_DATA_REQUEST'
export const GET_EMPLOYEES_DATA_SUCCESS='GET_EMPLOYEES_DATA_SUCCESS'
export const GET_EMPLOYEES_DATA_FAILURE='GET_EMPLOYEES_DATA_FAILURE'

export const GET_DESIGNATION_DATA_REQUEST='GET_DESIGNATION_DATA_REQUEST'
export const GET_DESIGNATION_DATA_SUCCESS='GET_DESIGNATION_DATA_SUCCESS'
export const GET_DESIGNATION_DATA_FAILURE='GET_DESIGNATION_DATA_FAILURE'

export const GET_PRIVILEGES_DATA_REQUEST='GET_PRIVILEGES_DATA_REQUEST'
export const GET_PRIVILEGES_DATA_SUCCESS='GET_PRIVILEGES_DATA_SUCCESS'
export const GET_PRIVILEGES_DATA_FAILURE='GET_PRIVILEGES_DATA_FAILURE'

export const SET_PREVILIGES_IN_STORE_REQUEST="SET_PREVILIGES_IN_STORE_REQUEST"
export const SET_PREVILIGES_IN_STORE_SUCCESS="SET_PREVILIGES_IN_STORE_SUCCESS"

export const SET_DESIGNATION_IN_STORE_REQUEST="SET_DESIGNATION_IN_STORE_REQUEST"
export const SET_DESIGNATION_IN_STORE_SUCCESS="SET_DESIGNATION_IN_STORE_SUCCESS"

export const GET_NOTIFICATION_DATA_REQUEST="GET_NOTIFICATION_DATA_REQUEST"
export const GET_NOTIFICATION_DATA_SUCCESS="GET_NOTIFICATION_DATA_SUCCESS"
export const GET_NOTIFICATION_DATA_FAILURE="GET_NOTIFICATION_DATA_FAILURE"


/*---------------------------Delivery Content Actions---------------------------------------------->*/
export const GET_CARRIER_DATA_REQUEST="GET_CARRIER_DATA_REQUEST"
export const GET_CARRIER_DATA_SUCCESS="GET_CARRIER_DATA_SUCCESS"
export const GET_CARRIER_DATA_FAILURE="GET_CARRIER_DATA_FAILURE"

export const GET_DELIVERY_SERVICE_DATA_REQUEST='GET_DELIVERY_SERVICE_DATA_REQUEST'
export const GET_DELIVERY_SERVICE_DATA_SUCCESS='GET_DELIVERY_SERVICE_DATA_SUCCESS'
export const GET_DELIVERY_SERVICE_DATA_FAILURE='GET_DELIVERY_SERVICE_DATA_FAILURE'

export const GET_CUSTOMER_SERVICE_DATA_REQUEST='GET_CUSTOMER_SERVICE_DATA_REQUEST'
export const GET_CUSTOMER_SERVICE_DATA_SUCCESS='GET_CUSTOMER_SERVICE_DATA_SUCCESS'
export const GET_CUSTOMER_SERVICE_DATA_FAILURE='GET_CUSTOMER_SERVICE_DATA_FAILURE'


/*---------------------------LOGS Content Actions---------------------------------------------->*/


export const GET_LOGS_CONTENT_REQUEST="GET_LOGS_CONTENT_REQUEST"
export const GET_LOGS_CONTENT_SUCCESS="GET_LOGS_CONTENT_SUCCESS"
export const GET_LOGS_CONTENT_FAILURE="GET_LOGS_CONTENT_FAILURE"


export const SET_PRIVILIGES_AT_LOGIN='SET_PRIVILIGES_AT_LOGIN'
export const SET_PRIVILIGES_AT_LOGIN_SUCCESS="SET_PRIVILIGES_AT_LOGIN_SUCCESS"

export const CREATE_NEW_USER_FOR_NOTIFICATION="CREATE_NEW_USER_FOR_NOTIFICATION"
export const CREATE_NEW_USER_FOR_NOTIFICATION_SUCCESS="CREATE_NEW_USER_FOR_NOTIFICATION_SUCCESS"


export const NEW_USER_CONNECTED_REQUEST="NEW_USER_CONNECTED_REQUEST"
export const NEW_USER_CONNECTED_SUCCESS="NEW_USER_CONNECTED_SUCCESS"

export const USER_DISCONNECTED_REQUEST="USER_DISCONNECTED_REQUEST"
export const USER_DISCONNECTED_SUCCESS="USER_DISCONNECTED_SUCCESS"

export const EMPLOYEE_CONNECTED_REQUEST="EMPLOYEE_CONNECTED_REQUEST"
export const EMPLOYEE_CONNECTED_SUCCESS="EMPLOYEE_CONNECTED_SUCCESS"


export const EMPLOYEE_DISCONNECTED_REQUEST="EMPLOYEE_DISCONNECTED_REQUEST"
export const EMPLOYEE_DISCONNECTED_SUCCESS="EMPLOYEE_DISCONNECTED_SUCCESS"
